language: node_js
node_js:
  - '14'
cache:
  directories:
    - 'node_modules'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local_dir: src
  on:
    branch: master
